server:
  port: 25565
  error:
    include-message: always
    include-stacktrace: never
  servlet:
    context-path: /api/v1
springdoc:
  packages-to-scan: ru.itmo.zavar.faccauth.controller
  paths-to-exclude: /profile/**, /roleEntities/**, /userEntities/**
  api-docs:
    path: /api-docs
spring:
  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    properties:
      hibernate:
        show_sql: false
    hibernate:
      ddl-auto: update
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:user_db}
    password: ${SPRING_DATASOURCE_PASSWORD:facc}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db-facc}
    driver-class-name: org.postgresql.Driver
  mvc:
    log-resolved-exception: true
    servlet:
      load-on-startup: 1
token:
  expire: 1440
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
admin:
  username: admin
  password: admin
yandex:
  auth-key-file: /authorized_key.json
  logging:
    enable: true
    host: ingester.logging.yandexcloud.net
    port: 443
    log-group-id: e23jts8dhh9aolg1at3p
    iam-key: t1.9euelZqJy5WKjImayprLkZaNlpacm-3rnpWalJuYmpKYz4nNl5yLk5uakszl8_diKXVT-e8MGClg_N3z9yJYclP57wwYKWD8zef1656VmpSSm87OipOVx5eYnI3Gx4yK7_zN5_XrnpWamZ2NkszPi8qQi5TOnI6Uipjv_cXrnpWalJKbzs6Kk5XHl5icjcbHjIo.4f_kZ1skT-WncGNYM_GpWep2RD_EyE5SHjrcoRSe9WhcdpYyO7jbQgZso6lYQgjmr8h7uuUmTrOzDF5jvunGBg