server:
  port: 25565
  error:
    include-message: always
    include-stacktrace: never
  servlet:
    context-path: /api/v1
springdoc:
  packages-to-scan: ru.itmo.zavar.faccauth.controller
  paths-to-exclude: /profile/**, /roleEntities/**, /userEntities/**
  api-docs:
    path: /api-docs
spring:
  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    properties:
      hibernate:
        show_sql: false
    hibernate:
      ddl-auto: update
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql}
    driver-class-name: org.postgresql.Driver
  mvc:
    log-resolved-exception: true
    servlet:
      load-on-startup: 1
token:
  expire: 1440
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
admin:
  username: admin
  password: admin
yandex:
  auth-key-file: /authorized_key.json
  log-group-id: e23jts8dhh9aolg1at3p
logging:
  level:
    root: trace
