server:
  port: 25565
  error:
    include-message: always
  servlet:
    context-path: /api/v1
springdoc:
  packages-to-scan: ru.itmo.zavar.faccauth.controller
  paths-to-exclude: /profile/**, /roleEntities/**, /userEntities/**
  api-docs:
    path: /api-docs
spring:
  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    username: user_db
    password: facc
    url: jdbc:postgresql://localhost:5432/db-facc
    driver-class-name: org.postgresql.Driver
token:
  expire: 24
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
admin:
  username: admin
  password: admin
