server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: never
  servlet:
    context-path: /api/v1
spring:
  sql:
    init:
      mode: always
  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    properties:
      hibernate:
        show_sql: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  datasource:
    username: user_db
    password: facc
    url: jdbc:postgresql://localhost:5432/db-facc
    driver-class-name: org.postgresql.Driver
  mvc:
    log-resolved-exception: true
logging:
  level:
    sql: off
status:
  enabled: "Enabled"
  disabled: "Disabled"
yandex:
  auth-key-file: /authorized_key.json
  log-group-id: e232s1431gbklopopjth
  speech-kit:
    api-key: AQVN0d46lvCEhtvxu40fPEQmEO6kfJ2MSWYaaC0b
    tts:
      host: tts.api.cloud.yandex.net
      port: 443
    stt:
      host: stt.api.cloud.yandex.net
      port: 443
