server:
  port: 25566
  error:
    include-message: always
    include-stacktrace: never
  servlet:
    context-path: /api/v1
spring:
  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    properties:
      hibernate:
        show_sql: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: user_db
    password: facc
    url: jdbc:postgresql://localhost:5432/db-facc
    driver-class-name: org.postgresql.Driver
  mvc:
    log-resolved-exception: true
logging:
  level:
    sql: debug
