server:
  port: 8080

#spring.sql.init.schema-locations=classpath:db/quartz_tables_h2.sql
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.username=sa
#spring.datasource.password=

spring:
  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    properties:
      hibernate:
        show_sql: false
    hibernate:
      ddl-auto: update
  datasource:
    username: user_db
    password: facc
    url: jdbc:postgresql://localhost:5432/db-facc
    driver-class-name: org.postgresql.Driver

logging:
  level:
    sql: debug
