server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: never
  servlet:
    context-path: /api/v1
springdoc:
  packages-to-scan: ru.itmo.zavar.controller
  api-docs:
    path: /api-docs
spring:
  sql:
    init:
      mode: always
  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    properties:
      hibernate:
        show_sql: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:user_db}
    password: ${SPRING_DATASOURCE_PASSWORD:facc}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db-facc}
    driver-class-name: org.postgresql.Driver
  mvc:
    log-resolved-exception: true
logging:
  level:
    sql: off
status:
  enabled: "Enabled"
  disabled: "Disabled"
yandex:
  auth-key-file: /authorized_key.json
  logging:
    enable: true
    host: ingester.logging.yandexcloud.net
    port: 443
    log-group-id: e232s1431gbklopopjth
    iam-key: t1.9euelZqJy5WKjImayprLkZaNlpacm-3rnpWalJuYmpKYz4nNl5yLk5uakszl8_diKXVT-e8MGClg_N3z9yJYclP57wwYKWD8zef1656VmpSSm87OipOVx5eYnI3Gx4yK7_zN5_XrnpWamZ2NkszPi8qQi5TOnI6Uipjv_cXrnpWalJKbzs6Kk5XHl5icjcbHjIo.4f_kZ1skT-WncGNYM_GpWep2RD_EyE5SHjrcoRSe9WhcdpYyO7jbQgZso6lYQgjmr8h7uuUmTrOzDF5jvunGBg
  mqtt:
    broker-url: ssl://mqtt.cloud.yandex.net:8883
    registry-id: arer55oi4m3l1tv2r7ig
  speech-kit:
    api-key: AQVN0d46lvCEhtvxu40fPEQmEO6kfJ2MSWYaaC0b
    tts:
      host: tts.api.cloud.yandex.net
      port: 443
    stt:
      host: stt.api.cloud.yandex.net
      port: 443
